const dataTable = [
  {
    id: 1,
    fecha: "2023-11-01",
    usuario: "Usuario A",
    localizacion: "Localización X",
    detalles: "Transito",
    fotoUrl: "https://picsum.photos/200?blur?random=2",
    condicion: "Reportado",
    movil: Math.floor(10000 + Math.random() * 90000), //
  },
  {
    id: 2,
    fecha: "2023-11-02",
    usuario: "Usuario B",
    localizacion: "Localización Y",
    detalles: "Incendio",
    fotoUrl: "https://picsum.photos/200?blur?random=1",
    condicion: "En Curso",
  },
  {
    id: 3,
    fecha: "2023-11-03",
    usuario: "Usuario C",
    localizacion: "Localización Z",
    detalles: "Inundacion",
    fotoUrl: "https://picsum.photos/200?blur?random=3",
    condicion: "En Curso",
  },
  {
    id: 4,
    fecha: "2023-11-04",
    usuario: "Usuario D",
    localizacion: "Localización W",
    detalles: "Ambulancia",
    fotoUrl: "https://picsum.photos/200?blur?random=4",
    condicion: "En Curso",
  },
  {
    id: 5,
    fecha: "2023-11-05",
    usuario: "Usuario E",
    localizacion: "Localización V",
    detalles: "Incendio",
    fotoUrl: "https://picsum.photos/200?blur?random=5",
    condicion: "En Curso",
  },
  {
    id: 6,
    fecha: "2023-11-06",
    usuario: "Usuario F",
    localizacion: "Localización U",
    detalles: "Ambulancia",
    fotoUrl: "https://picsum.photos/200?blur?random=6",
    condicion: "En Curso",
  },
  {
    id: 7,
    fecha: "2023-11-07",
    usuario: "Usuario G",
    localizacion: "Localización T",
    detalles: "Ambulancia",
    fotoUrl: "https://picsum.photos/200?blur?random=7",
    condicion: "En Curso",
  },
  {
    id: 8,
    fecha: "2023-11-08",
    usuario: "Usuario H",
    localizacion: "Localización S",
    detalles: "Transito",
    fotoUrl: "https://picsum.photos/200?blur?random=8",
    condicion: "En Curso",
  },
  {
    id: 9,
    fecha: "2023-11-09",
    usuario: "Usuario I",
    localizacion: "Localización R",
    detalles: "Transito",
    fotoUrl: "https://picsum.photos/200?blur?random=10",
    condicion: "En Curso",
  },
  {
    id: 10,
    fecha: "2023-11-10",
    usuario: "Usuario J",
    localizacion: "Localización Q",
    detalles: "Inundacion",
    fotoUrl: "https://picsum.photos/200?blur?random=11",
    condicion: "En Curso",
  },
];

export default dataTable;
